### ISSUE TITLE
Definiton of `8stream_merge' contains an unbound variable

### ISSUE THREAD

**Issue by JadLevesque** [rofl0r/order-pp#3]
There seems to be a typo in the definition of `8stream_merge' : https://github.com/rofl0r/order-pp/blob/0f81b9982c945ce70b57135b3e27c76453031c72/inc/order/lib/stream.h#L99 .

Replacing `8S` by `8R` solves the problem.

**Comment by rofl0r** [comment]
could you submit a PR pls ?

**Comment by JadLevesque** [comment]
I shall. Sorry, I a am new to github.

**Comment by mohawk2** [comment]
The code now has `8R` - this issue can be closed?

**Comment by rofl0r** [comment]
cb7086aa467863a36fa00a21b805c2a18c360e1c
